controls/urls.py
from django.contrib import admin
from django.urls import path
#from . import views

from .views import (
    #home,
    add_category,
    add_subcategory,
    add_setprice_item,
    add_setprice_category,
    utilities,
    mark_all_verified,
    mark_all_invoiced,
    missing_workorders,
    update_complete_date,
    special_tools,
    customer_shipto,
    workorder_ship,
    cust_history,
    cust_address,
    cust_wo_address,
    create_inventory_from_inventory,
    add_primary_vendor,
    add_units_per_base_unit,
    view_price_groups,
    view_price_group_detail,
    add_price_group,
    add_price_group_item,
    add_primary_baseunit,
    add_item_variation,
    add_base_qty_variation,
    add_internal_part_number,
    get_highest_item_price,
    items_missing_details,
    high_price_item,
    krueger_statements,
    krueger_ar_aging,
    add_to_item_list
    #setprice_list,
)

app_name='controls'

urlpatterns = [
    #path('', home, name='home'),
    path('add_category/', add_category, name='add_category'),
    path('add_subcategory/', add_subcategory, name='add_subcategory'),
    path('add_setprice_category/', add_setprice_category, name='add_setprice_category'),
    path('add_setprice_item/', add_setprice_item, name='add_setprice_item'),
    path('utilities/', utilities, name='utilities'),
    path('mark_verified/', mark_all_verified, name='mark_all_verified'),
    path('mark_invoiced/', mark_all_invoiced, name='mark_all_invoiced'),
    path('missing_workorders/', missing_workorders, name='missing_workorders'),
    path('update_complete_date/', update_complete_date, name='update_complete_date'),
    path('special_tools/', special_tools, name='special_tools'),
    path('customer_shipto/', customer_shipto, name='customer_shipto'),
    path('workorder_ship/', workorder_ship, name='workorder_ship'),
    path('cust_history/', cust_history, name='cust_history'),
    path('cust_address/', cust_address, name='cust_address'),
    path('cust_wo_address/', cust_wo_address, name='cust_wo_address'),
    path('create_inventory_from_inventory/', create_inventory_from_inventory, name='create_inventory_from_inventory'),
    path('add_primary_vendor/', add_primary_vendor, name='add_primary_vendor'),
    path('add_units_per_base_unit/', add_units_per_base_unit, name='add_units_per_base_unit'),
    path('view_price_groups/', view_price_groups, name='view_price_groups'),
    path('view_price_group_detail/<int:id>/', view_price_group_detail, name='view_price_group_detail'),
    #path('add_price_group/<int:id>', add_price_group, name='add_price_group'),
    path('add_price_group/', add_price_group, name='add_price_group'),
    # path('add_price_group_item/<int:id>/<str:list>', add_price_group_item, name='add_price_group_item'),
    # path('add_price_group_item/<int:id>', add_price_group_item, name='add_price_group_item'),
    # path('add_price_group_item/', add_price_group_item, name='add_price_group_item'),
    path('add_price_group_item/<int:id>/', add_price_group_item, name='add_price_group_item'),
    path('add_primary_baseunit/', add_primary_baseunit, name='add_primary_baseunit'),
    path('add_item_variation/', add_item_variation, name='add_item_variation'),
    path('add_base_qty_variation/', add_base_qty_variation, name='add_base_qty_variation'),
    path('add_internal_part_number/', add_internal_part_number, name='add_internal_part_number'),
    path('get_highest_item_price/', get_highest_item_price, name='get_highest_item_price'),
    path('items_missing_details/', items_missing_details, name='items_missing_details'),
    path('high_price_item/', high_price_item, name='high_price_item'),
    #path('setprice_list/', setprice_list, name='setprice_list'),
    path('krueger_statements/', krueger_statements, name='krueger_statements'),
    path('krueger_ar_aging/', krueger_ar_aging, name='krueger_ar_aging'),
    path('add_to_item_list/', add_to_item_list, name='add_to_item_list'),
]

pdf/urls.py
from django.urls import path

from .views import (
    invoice_pdf,
    lineitem_pdf,
    ticket_pdf,
    statement_pdf,
    statement_pdf_bulk,
    #

    ####### These aren't currently used
    render_pdf_view,
    CustomerListView, 
    customer_render_pdf_view,
    show_workorder_items,
    pdf_report_create,
    management,
    export_batch_statement_pdf,
    packing_slip,
    
)

app_name='pdf'

from . import views

urlpatterns = [
    #path('', views.newjob, name='krueger-print'),
    path('invoice_pdf/<int:id>/', invoice_pdf, name='invoice_pdf'),
    path('lineitem_pdf/<int:id>/', lineitem_pdf, name='lineitem_pdf'),
    path('statement_pdf/<int:id>/', statement_pdf, name='statement_pdf'),
    path('statement_pdf/', statement_pdf_bulk, name='statement_pdf_bulk'),
    path('ticket_pdf/<int:id>/', ticket_pdf, name='ticket_pdf'),
    ###### These aren't currently used
    path('', CustomerListView.as_view(), name='customer-list-view'),
    path('test/', render_pdf_view, name='test-view'),
    path('<pk>/', customer_render_pdf_view, name='customer-pdf-view'),
    path('showitems/', show_workorder_items, name='showitems'),
    path('pdfcreate/', pdf_report_create, name='create_pdf'),
    
    path('management/', management, name='management'),
    
    path('export_batch_statement_pdf/', export_batch_statement_pdf, name='export_batch_statement_pdf'),
    path('packing_slip/<int:id>/', packing_slip, name='packing_slip'),
]

pricesheet/urls.py
from django.urls import path

from .views import (
    envelope,
    template,
    template_list,
    add_template,
    subcategory,
    edititem,
    copy_template,
    remove_template,
    setprices,
    setqty,
    edit_wideformat_item,
    wideformat_template,
)

app_name='pricesheet'

from . import views

urlpatterns = [
    #path('', views.newjob, name='krueger-print'),
    path('envelope/<int:pk>/edit/<int:cat>', envelope, name='envelope'),
    path('template/<int:id>/', template, name='template'),
    path('wideformat_template/<int:id>/', wideformat_template, name='wideformat_template'),
    path('templates/', template_list, name='template_list'),
    path('templates/<int:id>', template_list, name='template_listing'),
    path('copy_template/', copy_template, name='copy_template'),
    path('add_template/', add_template, name='add_template'),
    path('subcategories/', subcategory, name='subcategory'),
    path('removetemplate/', remove_template, name='remove_template'),
    path('edititem/<int:id>/<int:pk>/<int:cat>/', edititem, name='edititem'),
    path('edit_wideformat_item/<int:pk>/<int:cat>/', edit_wideformat_item, name='edit_wideformat_item'),
    path('setprices/', setprices, name='setprices'),
    path('setqty/', setqty, name='setqty'),
]

studio_management/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

def trigger_error(request):
    division_by_zero = 1 / 0


from .views import home_view, search

urlpatterns = [
    path('', home_view, name='home'),
    path('search/', search, name='search'),
    path('sentry-debug/', trigger_error),
    path('admin/', admin.site.urls),
    path('controls/', include('controls.urls')),
    #path('accounts/', include('accounts.urls')),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path('customers/', include('customers.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('inventory/', include('inventory.urls')),
    path('finance/', include('finance.urls')),
    path('krueger/', include('krueger.urls')),
    path('onlinestore/', include('onlinestore.urls')),
    path('pdf/', include('pdf.urls')),
    path('pricesheet/', include('pricesheet.urls')),
    path('printleader/', include('printleader.urls')),
    path('retail/', include('retail.urls')),
    #path('vendors/', include('vendors.urls')),
    path('workorders/', include('workorders.urls')),
    

    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:  # keep this dev-only
    urlpatterns += [
        path("dev/", include(("devtools.urls", "devtools"), namespace="devtools")),
    ]

finance/forms.py
import calendar
from datetime import date
from django import forms
from django.forms import ModelForm
from django.urls import reverse_lazy
from .models import Payments, AccountsPayable, DailySales, Appliedother, InvoiceItem
from customers.models import Customer
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

class PaymentForm(forms.ModelForm):

    class Meta:
        model = Payments
        fields = ['date', 'customer', 'payment_type', 'amount', 'memo']

class AccountsPayableForm(forms.ModelForm):

    required_css_class = 'required-field'
    #name = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "Vendor name"}))
    #active = forms.BooleanField(widget=forms.CheckboxInput(attrs={"default": "True"}))
    class Meta:
        model = AccountsPayable
        fields = ['invoice_date', 'vendor', 'description', 'invoice_number', 'amount', 'date_due', 'discount', 'discount_date_due', 'paid', 'date_paid', 'amount_paid', 'payment_method', 'check_number', 'posted']


class DailySalesForm(forms.ModelForm):

    required_css_class = 'required-field'
    #name = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "Vendor name"}))
    #active = forms.BooleanField(widget=forms.CheckboxInput(attrs={"default": "True"}))
    class Meta:
        model = DailySales
        fields = ['date', 'cash', 'checks', 'creditcard', 'creditcard_fee', 'total']

class AppliedElsewhereForm(forms.ModelForm):

    class Meta:
        model = Appliedother
        fields = ['date', 'customer', 'amount', 'memo']

# class WorkorderPayment(forms.ModelForm):
#    #state = forms.CharField(widget=USStateSelect(), initial='WI')
#    class Meta:
#        model = WorkorderPayment
#        fields = ['workorder', 'payment', 'payment_amount', 'date']
#        labels = {
#         }

class AddInvoiceForm(forms.ModelForm):
   class Meta:
       model = AccountsPayable
       fields = ['invoice_date', 'invoice_number', 'description', 'total', 'date_due', 'discount', 'discount_date_due', 'paid', 'date_paid', 'amount_paid', 'payment_method', 'check_number']
       labels = {
        }
       
class EditInvoiceForm(forms.ModelForm):
   class Meta:
       model = AccountsPayable
       fields = ['invoice_date', 'invoice_number', 'description', 'vendor', 'total', 'date_due', 'discount', 'discount_date_due', 'paid', 'date_paid', 'amount_paid', 'payment_method', 'check_number', 'posted', 'void', 'void_reason']
       labels = {
        }
       
class BulkEditInvoiceForm(forms.ModelForm):
   class Meta:
       model = AccountsPayable
       fields = ['date_paid', 'payment_method', 'check_number']
       labels = {
        }
       
class AddInvoiceItemForm(forms.ModelForm):
   class Meta:
       model = InvoiceItem
       fields = ['name', 'vendor_part_number', 'description', 'internal_part_number', 'vendor', 'invoice_unit_cost', 'invoice_qty']
       labels = {
        }
       
       
class AddInvoiceItemRemainderForm(forms.ModelForm):
    class Meta:
        model = InvoiceItem
        fields = ['vendor_part_number', 'description', 'invoice_unit_cost', 'invoice_qty']
        labels = {
        } 

class DateRangeForm(forms.Form):
    start_date = forms.DateField(widget=forms.TextInput(attrs={'class': 'datepicker'}))
    end_date = forms.DateField(widget=forms.TextInput(attrs={'class': 'datepicker'}))

class SalesComparisonForm(forms.Form):
    period1_start = forms.DateField(
        label="Period 1 start",
        widget=forms.DateInput(attrs={"type": "date"}),
    )
    period1_end = forms.DateField(
        label="Period 1 end",
        widget=forms.DateInput(attrs={"type": "date"}),
    )
    period2_start = forms.DateField(
        label="Period 2 start",
        widget=forms.DateInput(attrs={"type": "date"}),
    )
    period2_end = forms.DateField(
        label="Period 2 end",
        widget=forms.DateInput(attrs={"type": "date"}),
    )

    customer = forms.ModelChoiceField(
        queryset=Customer.objects.order_by("company_name"),
        required=False,
        label="Customer (optional)",
        widget=forms.Select(attrs={"class": "form-select select2"}),
    )

    COMPANY_CHOICES = [
        ("Krueger Printing", "Krueger Printing"),
        ("LK Design", "LK Design"),
        ("Office Supplies", "Office Supplies"),
    ]
    companies = forms.MultipleChoiceField(
        label="Companies",
        required=False,
        choices=COMPANY_CHOICES,
        widget=forms.CheckboxSelectMultiple,
    )

    combine_companies = forms.BooleanField(
        label="Combine selected companies into one row per customer",
        required=False,
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        if not self.is_bound:
            today = date.today()

            # last month relative to today
            if today.month > 1:
                last_month = today.month - 1
                last_month_year = today.year
            else:
                last_month = 12
                last_month_year = today.year - 1

            # Last day of that last_month
            _, last_month_days = calendar.monthrange(last_month_year, last_month)
            last_month_end_this_year = date(last_month_year, last_month, last_month_days)

            # Period 2: Jan 1 of last_month_year → end of that last month
            period2_start = date(last_month_year, 1, 1)
            period2_end = last_month_end_this_year

            # Period 1: previous year, same structure
            year1 = last_month_year - 1
            _, last_month_days1 = calendar.monthrange(year1, last_month)
            period1_start = date(year1, 1, 1)
            period1_end = date(year1, last_month, last_month_days1)

            self.initial["period1_start"] = period1_start
            self.initial["period1_end"] = period1_end
            self.initial["period2_start"] = period2_start
            self.initial["period2_end"] = period2_end

        self.fields["customer"].empty_label = "All customers"

templates/pricesheet/list.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}

Pricing templates
<p>
{{ message }}
<p>

    <div class="row">
      <div class="col-md-3 mb-sm-0">
        <div id="category-info-card" class="card" hx-trigger="CategoryListChanged from:body" hx-get="{% url 'pricesheet:template_list'  %}" hx-target="this">
          {% include 'pricesheet/partials/category_list.html' %}
          </div>
      </div>
      <div class="col-md-3">
        <div id="contact-card" class="card" hx-trigger="SubcategoryListChanged from:body" hx-get="{% url 'pricesheet:template_list'  %}?category={{ category.id }}" hx-target="this">
          {% include 'pricesheet/partials/subcategory_list.html' %}
          </div>
      </div>
      <div class="col-md-3">
          <div id="workorder-info-card" class="card" hx-trigger="TemplateListChanged from:body" hx-get="{% url 'pricesheet:template_list'  %}?category={{ category.id }}" hx-target="this">
            {% include 'pricesheet/partials/template_list.html' %}
          </div>
      </div>
    </div>
    <button hx-get="{% url 'controls:add_category' %}" hx-target="#dialog" class="btn btn-primary">
        Add Category
        </button>
    <button hx-get="{% url 'controls:add_subcategory' %}" hx-target="#dialog" class="btn btn-primary">
        Add Subcategory
        </button>
    <button hx-get="{% url 'pricesheet:add_template' %}" hx-target="#dialog" class="btn btn-primary">
      Add Template
      </button>
<p>
  Instructions:<br/>
  Create a Category, then create a subcategory for the Category<br/>
  Create a template for the subcategory, and it will then appear in the list.<br/>
      <p>
  Click on an item. If it doesn't have a pricing template, it will ask you to create one.<br/>
  The pricing template will be used to fill out basic form info for the specified subcategory<br/>

<div id="modal" class="modal fade">
    <div id="dialog" class="modal-dialog" hx-target="this"></div>
</div>
    
<div id="modal2" class="modal fade">
    <div id="dialog2" class="modal-dialog modal-lg" hx-target="this"></div>
</div>



{% endblock content %}

{% block scripts %}

<script>

    $(document).ready(function () {
      $("#id_customer").select2();
      $('#id_customer').on('select2:select', (e) => {
        htmx.trigger("#id_customer", "change")
      });
    })

    const modal = new bootstrap.Modal(document.getElementById("modal"))

    htmx.on("htmx:afterSwap", (e) => {
      // Response targeting #dialog => show the modal
      if (e.detail.target.id == "dialog") {
        modal.show()
      }
    })

    htmx.on("htmx:beforeSwap", (e) => {
      // Empty response targeting #dialog => hide the modal
      if (e.detail.target.id == "dialog" && !e.detail.xhr.response) {
        modal.hide()
        e.detail.shouldSwap = false
      }
    })

    htmx.on("hidden.bs.modal", () => {
      document.getElementById("dialog").innerHTML = ""
    })
    

    const modal2 = new bootstrap.Modal(document.getElementById("modal2"))

    htmx.on("htmx:afterSwap", (e) => {
      // Response targeting #dialog => show the modal
      if (e.detail.target.id == "dialog2") {
        modal2.show()
      }
    })

    htmx.on("htmx:beforeSwap", (e) => {
      // Empty response targeting #dialog => hide the modal
      if (e.detail.target.id == "dialog2" && !e.detail.xhr.response) {
        modal2.hide()
        e.detail.shouldSwap = false
      }
    })

    htmx.on("hidden.bs.modal", () => {
      document.getElementById("dialog2").innerHTML = ""
    })


</script>

{% endblock %}